# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends openscad
      - name: install hbs
        run: npm install -g hbs-cli  
      - name: install MCAD models
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/openscad/MCAD/tarball/master -o ./mcad.tar.gz \
          && mkdir -p $GITHUB_WORKSPACE/MCAD \
          && tar -xf ./mcad.tar.gz -C $GITHUB_WORKSPACE/MCAD --strip-components 1 \
          && rm ./mcad.tar.gz
      - name: install fillet lib
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ademuri/openscad-fillets/tarball/main -o ./fillets.tar.gz \
          && mkdir -p $GITHUB_WORKSPACE/fillets \
          && tar -xf ./fillets.tar.gz -C $GITHUB_WORKSPACE/fillets --strip-components 1 \
          && rm ./fillets.tar.gz
      - name: setup node
        uses: actions/setup-node@v4
      - name: render
        run: | 
          #! /bin/bash

          set -e
          node $GITHUB_WORKSPACE/.github/index.mjs "$GITHUB_WORKSPACE"
          ls site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
